CREATE TABLE SHOPS(
SHOP_ID INT PRIMARY_KEY,
LOCATION VARCHAR(100),
CUISINE VARCHAR(50),
)

INSERT INTO TABLE SHOPS(LOCATION, CUISINE) VALUES ('KENSINGTON','FRENCH');
INSERT INTO TABLE SHOPS(LOCATION, CUISINE) VALUES ('KENSINGTON','ITALIAN');
INSERT INTO TABLE SHOPS(LOCATION, CUISINE) VALUES ('KENSINGTON','BRITISH');
INSERT INTO TABLE SHOPS(LOCATION, CUISINE) VALUES ('KENSINGTON','BEVERAGE');
INSERT INTO TABLE SHOPS(LOCATION, CUISINE) VALUES ('PICCADELLY','AMERICAN');
INSERT INTO TABLE SHOPS(LOCATION, CUISINE) VALUES ('PICCADELLY','SPANISH');
INSERT INTO TABLE SHOPS(LOCATION, CUISINE) VALUES ('PICCADELLY','BRISTISH');
INSERT INTO TABLE SHOPS(LOCATION, CUISINE) VALUES ('PICCADELLY','BEVERAGE');

CREATE TABLE ITEMS(
ITEM_ID INT PRIMARY_KEY,
ITEM_NAME VARCHAR(200),
CUISINE VARCHAR(50),
PRICE INT,
TYPE VARCHAR(50)
)

INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('CROISSANT','FRENCH',5,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('PAIN AU CHOCOLAT','FRENCH',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('BRIOCHE','FRENCH',3,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('CREPES','FRENCH',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('QUICHE','FRENCH',5,'SAVOURY');

INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('CANNOLI','ITALIAN',5,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('BAKLAVA','ITALIAN',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('CHOUX PASTRY','ITALIAN',3,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('SEMIFREDDO','ITALIAN',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('KOUIGNAMANN','ITALIAN',5,'SAVOURY');

INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('CORNISH PASTIES','BRITISH',5,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('STICKY TOFFEE PUDDING','BRITISH',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('ECLAIR','BRITISH',3,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('CHELSEA BUNS','BRITISH',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('SHEPHERDS PIE','BRITISH',5,'SAVOURY');

INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('LECHE FRITA','SPANISH',5,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('MIGUELITOS','SPANISH',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('TORRIJAS','SPANISH',3,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('FARTONS','SPANISH',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('SHRIMP EMPANADAS','SPANISH',5,'SAVOURY');

INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('PANCAKES','AMERICAN',5,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('CINNAMON ROLLS','AMERICAN',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('DOUGHNUT','AMERICAN',3,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('HAZELNUT BROWNIE','AMERICAN',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('SALMON BAGEL','AMERICAN',5,'SAVOURY');

INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('CAPPUCINO','BEVERAGE',3,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('ESPRESSO','BEVERAGE',2,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('HOT CHOCOLATE','BEVERAGE',4,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('BLACK TEA','BEVERAGE',2,'SWEET');
INSERT INTO TABLE ITEMS(ITEM_NAME, CUISINE, PRICE, TYPE) VALUES ('MILK TEA','BEVERAGE',3,'SWEET');

CREATE TABLE CLASSES (
CLASS_ID INT PRIMARY_KEY,
LOCATION VARCHAR(100),
CUISINE VARCHAR(50),
SEATS_AVAILABLE INT,
DATE VARCHAR(50),
SLOT VARCHAR(50)
)

INSERT INTO TABLE CLASSES(LOCATION, CUISINE, SEATS_AVAILABLE,DATE,SLOT) VALUES ('KENSINGTON','BRITISH',15,'15-JUNE-2020','10AM-12PM');
INSERT INTO TABLE CLASSES(LOCATION, CUISINE, SEATS_AVAILABLE,DATE,SLOT) VALUES ('PICCADELLY','FRENCH',10,'10-JUNE-2020','11AM-1PM');
INSERT INTO TABLE CLASSES(LOCATION, CUISINE, SEATS_AVAILABLE,DATE,SLOT) VALUES ('WESTMINSTER','ITALIAN',12,'12-JUNE-2020','12PM-2PM');
INSERT INTO TABLE CLASSES(LOCATION, CUISINE, SEATS_AVAILABLE,DATE,SLOT) VALUES ('CANARY WHARF','AMERICAN',17,'17-JUNE-2020','2PM-4PM');
INSERT INTO TABLE CLASSES(LOCATION, CUISINE, SEATS_AVAILABLE,DATE,SLOT) VALUES ('COVENT GARDEN','SPANISH',19,'19-JUNE-2020','3PM-5PM');

CREATE TABLE PARTIES (
PARTY_ID INT PRIMARY_KEY,
GUESTS INT,
LOCATION VARCHAR(200),
CUISINE_ONE VARCHAR(50),
CUISINE_TWO VARCHAR(50),
CUISINE_THREE VARCHAR(50),
TYPE VARCHAR(100),
PACKAGE INT
)

INSERT INTO TABLE PARTIES(GUESTS, LOCATION, CUISINE, TYPE, PACKAGE) VALUES (50,'ELEANOR ROAD','BRITISH','ITALIAN','FRENCH','WEDDING',750);
INSERT INTO TABLE PARTIES(GUESTS, LOCATION, CUISINE, TYPE, PACKAGE) VALUES (30,'SURREY','AMERICAN','FRENCH','NA','BABY SHOWER',450);
INSERT INTO TABLE PARTIES(GUESTS, LOCATION, CUISINE, TYPE, PACKAGE) VALUES (15,'SOHO','SPANISH','NA','NA','BACHELORETTE',250);

CREATE TABLE CUSTOMER (
CUST_ID INT PRIMARY_KEY,
NAME VARCHAR(100),
ADDRESS VARCHAR(200),
EMAIL VARCHAR(100),
PHONE VARCHAR(15),
MEMBERSHIP VARCHAR(50),
DISCOUNT INT
)

INSERT INTO TABLE CUSTOMER(NAME,ADDRESS,EMAIL,PHONE,MEMBERSHIP,DISCOUNT) VALUES ('JANE DOE','EARL STREET','JANE.DOE@GMAIL.COM','9887766550','SUPER',20);
INSERT INTO TABLE CUSTOMER(NAME,ADDRESS,EMAIL,PHONE,MEMBERSHIP,DISCOUNT) VALUES ('JOHN DAW','BRICK LANE','DOE.JOHN@YAHOO.IN','9443322110'.'NEW',10);

CREATE TABLE ORDERS (
ORDER_ID INT PRIMARY_KEY,
CATEGORY VARCHAR(50),
DATE VARCHAR(50),
AMOUNT INT,
PAYMENT_MODE VARCHAR(20),
SHOP_ID FOREIGN_KEY,
CUST_ID FOREIGN_KEY,
ITEMS VARCHAR(300),
CLASS_ID FOREIGN_KEY,
PARTY_ID FOREIGN_KEY,
DELIVERY_MODE VARCHAR(100),
ORDER_STATUS VARCHAR(100)
)

